language: node_js

before_script:
  - sudo apt-get install -qq pdftk
  - sudo apt-get install -qq tesseract-ocr
  - which tesseract
  - cat ./share/configs/alphanumeric
  
  - ls -R /usr/local/share/
  
node_js:
  - "0.8"
